# Generated by Django 4.1.2 on 2022-10-05 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Type",
            fields=[
                ("kind", models.BigAutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=50)),
                (
                    "nature",
                    models.CharField(
                        choices=[("Entrada", "Inflow"), ("Saída", "Outflow")],
                        max_length=50,
                    ),
                ),
                (
                    "sinal",
                    models.CharField(
                        choices=[("+", "Inflow"), ("-", "Outflow")], max_length=50
                    ),
                ),
            ],
            options={
                "ordering": ["-kind"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("amount", models.FloatField()),
                ("cpf", models.CharField(max_length=11)),
                ("card", models.CharField(max_length=12)),
                ("shop_owner", models.CharField(max_length=14)),
                ("shop_name", models.CharField(max_length=19)),
                (
                    "transaction_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="parser.type",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
